# Generated by Django 4.1 on 2022-11-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_deporte_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='cantidad_mundiales',
            new_name='cantidad_medallas',
        ),
    ]
